version: "3"

services:
  app:
    image: php:8.1.10-fpm
    container_name: php-fpm_host
    ports:
      - 8080:80
    #volumes:
    #    - .:/var/www/html
    #    - ./docker/app/php.ini:/usr/local/etc/php/php.ini
    tmpfs:
      - /run/php-fpm
